# Generated by Django 4.1 on 2022-09-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="NewUser", new_name="User",),
    ]
