# Generated by Django 4.1 on 2022-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_newuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
