# Generated by Django 4.1 on 2022-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_remove_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
