# Generated by Django 4.1 on 2022-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_remove_user_company_alter_user_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
