# Generated by Django 4.1 on 2022-09-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_alter_user_level_alter_user_residence_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="NewUser",),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=150, null=True)),
                ("level", models.CharField(max_length=150, null=True)),
                ("link", models.CharField(max_length=150, null=True)),
                ("description", models.CharField(max_length=150, null=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.newuser"
                    ),
                ),
            ],
        ),
    ]
