# Generated by Django 4.1 on 2022-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0013_resources_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="company",
            field=models.CharField(default=" ", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="level",
            field=models.CharField(default=" ", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="residence",
            field=models.CharField(default=" ", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="university",
            field=models.CharField(default=" ", max_length=150, null=True),
        ),
    ]
